name: "yarn-build-action"
description: "Sets up, builds, lints, and tests a node package using Yarn3 and Node 18"

inputs:
  npm-token:
    description: "npm credentials, most useful for private repositories"
    required: true

  skip-test:
    description: "Set to true if building for deploy and tests passed in another step"
    required: false
    default: false

  skip-lint:
    description: "Set to true if lint is not required/supported/needed"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'

    - name: Setup .yarnrc.yml
      shell: bash
      run: |
        yarn config set npmScopes.gasbuddy.npmRegistryServer "https://registry.npmjs.org"
        yarn config set npmScopes.gasbuddy.npmAlwaysAuth true
        yarn config set npmScopes.gasbuddy.npmAuthToken $NPM_AUTH_TOKEN
      if: "${{ inputs.npm_token != '' }}"
      env:
        NPM_AUTH_TOKEN: ${{inputs.npm-token}}

    - run: yarn install --immutable
      shell: bash

    - run: yarn lint
      shell: bash
      if: ${{ inputs.skip-lint != 'true' }}

    - run: yarn build
      shell: bash

    - run: yarn test
      shell: bash
      if: ${{ inputs.skip-test != 'true' }}
      env:
        NODE_ENV: test
        CI: true
